export const InterprocessCommand = {
  EXPLAIN_TOPIC: "EXPLAIN_TOPIC",
  DID_EXPLAIN_TOPIC: "DID_EXPLAIN_TOPIC",

  GENERATE_CARDS: "GENERATE_CARDS",
  DID_GENERATE_CARDS: "DID_GENERATE_CARDS",
  FAILED_GENERATE_CARDS: "FAILED_GENERATE_CARDS",

  ADD_CARDS: "ADD_CARDS",
  DID_ADD_CARDS: "DID_ADD_CARDS",

  ASK_CONVERSATION_DOCUMENTS: "ASK_CONVERSATION_DOCUMENTS",
  DID_ASK_CONVERSATION_DOCUMENTS: "DID_ASK_CONVERSATION_DOCUMENTS",

  ASK_CONVERSATION_NO_DOCUMENTS: "ASK_CONVERSATION_NO_DOCUMENTS",
  DID_ASK_CONVERSATION_NO_DOCUMENTS: "DID_ASK_CONVERSATION_NO_DOCUMENTS",

  CLEAR_CONVERSATION: "CLEAR_CONVERSATION",
  DID_CLEAR_CONVERSATION: "DID_CLEAR_CONVERSATION",

  ADD_DOCUMENTS: "ADD_DOCUMENTS",
  DID_ADD_DOCUMENTS: "DID_ADD_DOCUMENTS",

  DELETE_ALL_DOCUMENTS: "DELETE_ALL_DOCUMENTS",
  DID_DELETE_ALL_DOCUMENTS: "DID_DELETE_ALL_DOCUMENTS",

  OPEN_DOCUMENT_BROWSER: "OPEN_DOCUMENT_BROWSER",
  DID_CLOSE_DOCUMENT_BROWSER_NO_SELECTIONS:
    "DID_CLOSE_DOCUMENT_BROWSER_NO_SELECTIONS",
  DID_SELECT_DOCUMENTS: "DID_SELECT_DOCUMENTS",

  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
  DID_UPLOAD_DOCUMENT: "DID_UPLOAD_DOCUMENT",

  SPLIT_DOCUMENT: "SPLIT_DOCUMENT",
  DID_SPLIT_DOCUMENT: "DID_SPLIT_DOCUMENT",

  SET_OPENAI_API_KEY: "SET_OPENAI_API_KEY",
  DID_SET_OPENAI_API_KEY: "DID_SET_OPENAI_API_KEY",

  EDIT_SETTING: "EDIT_SETTING",
  DID_EDIT_SETTING: "DID_EDIT_SETTING",

  SET_LLM_MODEL: "SET_LLM_MODEL",
  DID_SET_LLM_MODEL: "DID_SET_LLM_MODEL",

  SET_TEMPERATURE: "SET_TEMPERATURE",
  DID_SET_TEMPERATURE: "DID_SET_TEMPERATURE",

  DID_LOAD_OLLAMA_MODELS: "DID_LOAD_OLLAMA_MODELS",
  DID_LOAD_SETTINGS: "DID_LOAD_SETTINGS",
  DID_FINISH_STARTUP: "DID_FINISH_STARTUP",

  SET_WEBAPP_LOADING: "SET_WEBAPP_LOADING",
  SET_WEBAPP_LOADING_TEXT: "SET_WEBAPP_LOADING_TEXT",

  NETWORK_REQUEST: "NETWORK_REQUEST",
  DID_NETWORK_REQUEST: "DID_NETWORK_REQUEST",

  PRINT_FROM_JS: "PRINT_FROM_JS",
  PRINT_FROM_SUBMODULE: "PRINT_FROM_SUBMODULE",

  SUBMODULE_ERROR: "SUBMODULE_ERROR",

  STOP_LOADERS: "STOP_LOADERS",

  ERROR: "ERROR",
};
