export const InterprocessCommand = {
  EXPLAIN_TOPIC: "EXPLAIN_TOPIC",
  DID_EXPLAIN_TOPIC: "DID_EXPLAIN_TOPIC",

  GENERATE_CARDS: "GENERATE_CARDS",
  DID_GENERATE_CARDS: "DID_GENERATE_CARDS",
  FAILED_GENERATE_CARDS: "FAILED_GENERATE_CARDS",

  ADD_CARDS: "ADD_CARDS",
  DID_ADD_CARDS: "DID_ADD_CARDS",

  ASK_CONVERSATION_DOCUMENTS: "ASK_CONVERSATION_DOCUMENTS",
  DID_ASK_CONVERSATION_DOCUMENTS: "DID_ASK_CONVERSATION_DOCUMENTS",

  ASK_CONVERSATION_NO_DOCUMENTS: "ASK_CONVERSATION_NO_DOCUMENTS",
  DID_ASK_CONVERSATION_NO_DOCUMENTS: "DID_ASK_CONVERSATION_NO_DOCUMENTS",

  CLEAR_CONVERSATION: "CLEAR_CONVERSATION",
  DID_CLEAR_CONVERSATION: "DID_CLEAR_CONVERSATION",

  ADD_DOCUMENTS: "ADD_DOCUMENTS",
  DID_ADD_DOCUMENTS: "DID_ADD_DOCUMENTS",

  DELETE_ALL_DOCUMENTS: "DELETE_ALL_DOCUMENTS",
  DID_DELETE_ALL_DOCUMENTS: "DID_DELETE_ALL_DOCUMENTS",

  OPEN_DOCUMENT_BROWSER: "OPEN_DOCUMENT_BROWSER",
  DID_CLOSE_DOCUMENT_BROWSER_NO_SELECTIONS:
    "DID_CLOSE_DOCUMENT_BROWSER_NO_SELECTIONS",
  DID_SELECT_DOCUMENTS: "DID_SELECT_DOCUMENTS",

  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
  DID_UPLOAD_DOCUMENT: "DID_UPLOAD_DOCUMENT",

  SPLIT_DOCUMENT: "SPLIT_DOCUMENT",
  DID_SPLIT_DOCUMENT: "DID_SPLIT_DOCUMENT",

  RESOLVE_IMAGES: "RESOLVE_IMAGES",
  DID_RESOLVE_IMAGES: "DID_RESOLVE_IMAGES",

  RESOLVE_AUDIO_IDS: "RESOLVE_AUDIO_IDS",
  DID_RESOLVE_AUDIO_IDS: "DID_RESOLVE_AUDIO_IDS",

  // AnkiBrain Voice (Kokoro TTS) — client-side in BOTH user modes.
  ADD_TTS_AUDIO: "ADD_TTS_AUDIO",
  SYNTHESIZE_SPEECH: "SYNTHESIZE_SPEECH",
  DID_SYNTHESIZE_SPEECH: "DID_SYNTHESIZE_SPEECH",
  TTS_STATUS: "TTS_STATUS",
  DID_TTS_STATUS: "DID_TTS_STATUS",
  TTS_INSTALL: "TTS_INSTALL",
  DID_TTS_INSTALL: "DID_TTS_INSTALL",
  TTS_INSTALL_PROGRESS: "TTS_INSTALL_PROGRESS", // push: bootstrap stage event
  TTS_INSTALL_DONE: "TTS_INSTALL_DONE", // push: {ok, error?}
  TTS_CANCEL_INSTALL: "TTS_CANCEL_INSTALL",
  TTS_UNINSTALL: "TTS_UNINSTALL",
  DID_TTS_UNINSTALL: "DID_TTS_UNINSTALL", // promise ack: {ok, error?}

  // Card audio (review-screen workflow): GENERATE_CARD_AUDIO {items} is
  // answered per clip by pushed CARD_AUDIO_RESULT events, then the batch
  // ack DID_GENERATE_CARD_AUDIO settles the request promise.
  GENERATE_CARD_AUDIO: "GENERATE_CARD_AUDIO",
  CARD_AUDIO_RESULT: "CARD_AUDIO_RESULT",
  DID_GENERATE_CARD_AUDIO: "DID_GENERATE_CARD_AUDIO",
  CANCEL_CARD_AUDIO: "CANCEL_CARD_AUDIO",
  DID_CANCEL_CARD_AUDIO: "DID_CANCEL_CARD_AUDIO",

  SET_OPENAI_API_KEY: "SET_OPENAI_API_KEY",
  DID_SET_OPENAI_API_KEY: "DID_SET_OPENAI_API_KEY",

  EDIT_SETTING: "EDIT_SETTING",
  DID_EDIT_SETTING: "DID_EDIT_SETTING",

  SET_LLM_MODEL: "SET_LLM_MODEL",
  DID_SET_LLM_MODEL: "DID_SET_LLM_MODEL",

  SET_TEMPERATURE: "SET_TEMPERATURE",
  DID_SET_TEMPERATURE: "DID_SET_TEMPERATURE",

  DID_LOAD_SETTINGS: "DID_LOAD_SETTINGS",
  DID_FINISH_STARTUP: "DID_FINISH_STARTUP",

  SET_WEBAPP_LOADING: "SET_WEBAPP_LOADING",
  SET_WEBAPP_LOADING_TEXT: "SET_WEBAPP_LOADING_TEXT",

  NETWORK_REQUEST: "NETWORK_REQUEST",
  DID_NETWORK_REQUEST: "DID_NETWORK_REQUEST",

  PRINT_FROM_JS: "PRINT_FROM_JS",
  PRINT_FROM_SUBMODULE: "PRINT_FROM_SUBMODULE",

  SUBMODULE_ERROR: "SUBMODULE_ERROR",

  STOP_LOADERS: "STOP_LOADERS",

  ERROR: "ERROR",
};
