import { store } from "../redux";
import { postChat } from "./networking/chat";
import { infoToast } from "../toast";

function buildBasicCardQuery(text, customPrompt, language = "English") {
  return `
    Please read the ${language} text below in quotes:
    
    "${text}"
    
    From the text above, I want you to create flash cards in ${language}. 
    Output in JSON format, using the following as a strict template for your response format:
            
    [
    {
      "front": "This is an example of the front of a card generated by ChatGPT to query the material. You can be creative about the best way to ask a question.",
      "back": "This is the back of the card that is the answer to the front." 
    }, 
    {
      "front": "This is the front of another card.",
      "back": "This is the back of another card."
    }
    ] 
    
    ${
      language !== "English"
        ? "The example given above is in English, but remember to translate the final cards into " +
          language +
          ". The names of the JSON fields ('front' and 'back') should remain in English."
        : ""
    }
    
    ${customPrompt}
             
    Do not output any other text besides JSON. Begin output now following the template above.
    `;
}

function buildClozeCardQuery(text, customPrompt, language = "English") {
  return `
    Please read the ${language} text below in quotes.
            
    "${text}"
    
    From the text above, I want you to create flash cards in ${language}. 
    These are special cards where you omit key words or phrases. 
    You can use asterisks *like this* to indicate that a word or phrase 
    should be hidden for whoever is studying the card. 
    You can create multiple deletions (omissions) per card. 
    Please decide to hide key words or phrases depending on how important they are to the context. 
    If a word or phrase is very important, you should definitely hide it using *this notation*!
    
    Output in JSON format, using the following as a strict template for your response format:
    
    [ 
    {
      "text": "This is an example of a *flash card* made by you."
    }, 
    {
      "text": "This is the *second* flash *card*, this time containing *three deletions*." 
    } 
    ] 
    
    I want each card to be relatively small - that means your "text" field should not be more than one sentence.
    You MUST have at least ONE deletion per flash card using *this notation*.
    
    ${
      language !== "English"
        ? "The example given above is in English, but remember to translate the final cards into " +
          language +
          ". The names of the JSON fields ('text') should remain in English."
        : ""
    }
    
    ${customPrompt}
  
    Do not produce any cards that lack a deletion. 
    Do not output any other text besides JSON. Begin output now following the template above.
    `;
}

export function generateCardsRequest(
  text,
  customPrompt,
  cardType,
  language = store.getState().language.value
) {
  if (!store.getState().user.value) {
    infoToast("Log in required", "Please log in first.");
    return;
  }

  let query;
  if (cardType === "basic") {
    query = buildBasicCardQuery(text, customPrompt, language);
  } else if (cardType === "cloze") {
    query = buildClozeCardQuery(text, customPrompt, language);
  } else return;

  return postChat(
    query,
    [],
    false,
    store.getState().appSettings.ai.llmModel,
    store.getState().appSettings.ai.temperature,
    store.getState().user.value.accessToken
  );
}
